FROM registry.docker.local/mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

RUN dotnet publish PowerMage.Collector/PowerMage.Collector.csproj \
    -c Release \
    -o /app/publish

FROM registry.docker.local/mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "PowerMage.Collector.dll"]